### ISSUE TITLE
Limit var definitions to `:root`

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-vars#15]
- [x] Enforce global variables by ignoring anything not declared in `:root`.
- [x] Collect all `:root` var definitions before replacement, to mimic all-at-once resolution of variable precedence.

**Comment by ianstormtaylor** [comment]
for reference, https://gist.github.com/chriseppstein/8013073

**Comment by ianstormtaylor** [comment]
oh and would also solve this, https://gist.github.com/chriseppstein/8012929

**Comment by chriseppstein** [comment]
IMO, if you just ignore scoped variable values, you're still hurting more than helping. It should be an error or it should go into "hands-off" mode for that variable and leave it to the browser to resolve.

Here's another brain teaser:

``` css
:root {
  var-grid-width: 40px;
}

@media screen and (max-device-width: 320px) {
  :root {
    var-grid-width: 10px;
  }
}

div.span-5 {
  width: calc(var(grid-width) * 5);
}
```

I'd expect the following output:

``` css
div.span-5 {
  width: 200px;
}
@media screen and (max-device-width: 320px) {
  div.span-5 {
    width: 50px;
  }
}
```

But instead, you get:

``` css
@media screen and (max-device-width: 320px) {

}

div.span-5 {
  width: 50px;
}
```
