### ISSUE TITLE
Decide on how to handle variables with @media blocks

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-vars#17]
https://github.com/visionmedia/rework-vars/issues/15#issuecomment-30801783

/ht @chriseppstein

**Comment by MoOx** [comment]
I'm interested to get :root vars in @media parsed. This make sense & I think we can take care of that. In a way it still :root like & we don't need to guess dom or something (but maybe I miss a use case).
See https://github.com/segmentio/myth/issues/58

**Comment by necolas** [comment]
The problem is when you have this:

``` css
:root {
  --font-size: 2em;
}

.Section {
  font-size: var(--font-size);
}

@media (min-width: 64em) {
  :root {
    --font-size: 3em;
  }
}
```

because now we need to inject the `.Section` rule into the media query and update the `font-size` in the output. it's just not great.

**Comment by MoOx** [comment]
I agree it's not that great, but it's seems to be our only option.
That being said, it make sense to me to behave that way. This will be particularly interesting if we use `@import` scoped by a media query. Don't you think ?

**Comment by carlcs** [comment]
Please make this happen. I'd so love to `@import` size-specific variants of my components at their corresponding media query breakpoints. Not being able to implement variables in these components keeps me from doing so.

@MoOx thanks for moving [the issue](https://github.com/segmentio/myth/issues/58) to the right place. And I definitely agree with you that the behavior @necolas pointed out is what I would have expected. You'd have to define the `.Section` rule again in the media query to get `font-size: 3em;` applied.

**Comment by necolas** [comment]
Variables are applied within media queries. You just can't reset variables with media queries.

**Comment by carlcs** [comment]
True, but this also means that I can't define variable defaults in the component and only overwrite them if necessary (I am trying to stick as close as possible to your wonderful Suit CSS methodologies with my components).

**Comment by necolas** [comment]
Do you have an example to help me better understand?

**Comment by MoOx** [comment]
`component.css`

``` css
:root {
  --X-size: 1rem;
}

.X {
  width: var(--X-size);
  other: rule;
}
```

`component-s.css`

``` css
:root {
  --X-size: .5rem;
}
```

`index.css`

``` css
@import "component.css";
@import "component-s.css" (max-width: 30em);
```

I would expect 

``` css
.X {
  width: 1rem;
  other: rule;
}

@media (max-width: 30em) {
  .X {
    width: .5rem;
  }
}
```

Btw it make me think that rules injection could be used to drop :root limitation by injecting new selectors with just appropriate rules (not sure what I'm missing).

**Comment by necolas** [comment]
Yeah that's what I'm saying here: https://github.com/reworkcss/rework-vars/issues/17#issuecomment-46698855. It could end up producing a lot of extra CSS in the output but might be worth adding as a feature to see if its useful.

I don't think media queries are good in most components. But I know that's a popular was to do "responsive design".

**Comment by carlcs** [comment]
Do you really need it to inject the ruleset? I can imagine this being rather unpredictable and actually planned to duplicate the rules directly into the component variants (cf. [suitcss/utils-size](https://github.com/suitcss/utils-size/tree/master/lib)) or `@import` a shared ruleset (didn't try that yet).

**Comment by necolas** [comment]
> Do you really need it to inject the ruleset?

You would because that would be part of mimicing how it works natively. I don't want to knowingly introduce changes to this module that render it incompatible with native CSS variables.

**Comment by njj** [comment]
How would something like the following be solved?

``` css
:root {
    --screen-sm-min: 768px;
}

@media (min-width: var(--screen-sm-min)) {
  .full-width-section {
    padding-left: 35px;
  }
}
```
