### ISSUE TITLE
Add an option to keep definition & var() usage in output

### ISSUE THREAD

**Issue by MoOx** [reworkcss/rework-vars#28]
Since browsers will implement this (Firefox 31 already have --syntax support), it could be great to add interpreted variables values just as a fallback.

``` css
:root {
    --color-one: blue;
}
.elem {
    color: var(--color-one);
}
```

yields:

``` css
:root {
    --color-one: blue;
}
.elem {
    color: blue;
    color: var(--color-one);
}
```

Are you open to that behavior ? Eventually with an option ?
