### ISSUE TITLE
Drop :root limitation using new selector/rules injections ?

### ISSUE THREAD

**Issue by MoOx** [reworkcss/rework-vars#30]
Like said [here](https://github.com/reworkcss/rework-vars/issues/17#issuecomment-46773198) I was that dropping :root limitation should be that hard using selector injection like it has been already said in other issues. This could also fix #17

``` css
:root {
  --mainColor: red;
}

a {
  color: var(--mainColor);
  other: rule;
}

p {
  --mainColor: blue;
  border: 1px solid var(--mainColor)
}
```

I would expect 

``` css
a {
  color: red;
  other: rule;
}

p {
  border: 1px solid blue;
}

p a {
  color: blue;
}
```

Not sure about what I'm missing. I know we cant guess dom & so update appropriate result, but we could inject new selectors with rules that make use of var() like in the example above.
Obviously that can represent a huge amount of selectors to add if there is a lot of variable & a lot of usage, but that will do the job "as expected".

I was thinking of an incoming issue with #id selectors related to injection but can't remind it right now it's too early in the morning here.
