### ISSUE TITLE
Variables not applied to @media queries

### ISSUE THREAD

**Issue by conradz** [reworkcss/rework-vars#31]
Variables are not applied to `@media` queries. In the following example the `var(--test)` is not changed at all when passed through `rework-vars`:

``` css
:root {
  --test: 500px;
}

@media (min-width: var(--test)) {
  .test {
    width: 100px;
  }
}
```

This was brought up in reworkcss/rework-custom-media#3. It is slightly different from #17, since this covers variables in the _query_, not in the query block that follows.

I'm not sure that this is covered by the [W3C spec](http://dev.w3.org/csswg/css-variables/#using-variables), @necolas do you know how the spec says this should work?

/cc @jasonkuhrt
