### ISSUE TITLE
Issue with comments in @keyframes

### ISSUE THREAD

**Issue by MoOx** [reworkcss/rework-vars#32]
Related to https://github.com/segmentio/myth/issues/48#issuecomment-50252938

Adding a comment in after a keyframe create an issue because rework-visit returns `null` for the corresponding `declarations`.

``` css
:root {
  --op-start: 0;
  --op-end: 1;
}

@keyframes kf {
    0%   { opacity: var(--op-start) }
    25%  { opacity: var(--op-start) }  /* remove me will remove the issue below */
    100% { opacity: var(--op-end) }
}
```

```
     TypeError: Cannot read property 'length' of undefined
      at ~/rework-vars/index.js:58:39
      at ~/rework-vars/node_modules/rework-visit/index.js:28:9
      at Array.forEach (native)
      at ~/rework-vars/node_modules/rework-visit/index.js:27:22
      at Array.forEach (native)
      at visit (~/rework-vars/node_modules/rework-visit/index.js:18:14)
      at vars (~/rework-vars/index.js:53:5)
      at Rework.use (~/rework-vars/node_modules/rework/index.js:49:3)
      at compareFixtures (~/rework-vars/test/test.js:11:38)
      at Context.<anonymous> (~/rework-vars/test/test.js:47:5)
      at Test.Runnable.run (~/rework-vars/node_modules/mocha/lib/runnable.js:211:32)
      at Runner.runTest (~/rework-vars/node_modules/mocha/lib/runner.js:358:10)
      at ~/rework-vars/node_modules/mocha/lib/runner.js:404:12
      at next (~/rework-vars/node_modules/mocha/lib/runner.js:284:14)
      at ~/rework-vars/node_modules/mocha/lib/runner.js:293:7
      at next (~/rework-vars/node_modules/mocha/lib/runner.js:237:23)
      at Object._onImmediate (~/rework-vars/node_modules/mocha/lib/runner.js:261:5)
      at processImmediate [as _immediateCallback] (timers.js:336:15)
```
