### ISSUE TITLE
Comments in rule sets for variable definitions

### ISSUE THREAD

**Issue by carlcs** [reworkcss/rework-vars#34]
All `:root {}` rule sets with variable definitions are generally removed from the output. But not so if they contain comments. Aiming for a clean CSS file, I'd like to have an option to have these sets (and the comments) removed, too.

``` css
:root {
  /* Font stacks */
  --font-family-sans: "Proxima Nova", sans-serif;
  --font-family-serif: serif;
  --font-family-mono: monospace;

  /* More font variables */
  --font-var: normal;
}
:root {
  --var: normal;
}
```

``` css
:root {
  /* Font stacks */

  /* More font variables */
}
```
