### ISSUE TITLE
:root.className[attr] selector

### ISSUE THREAD

**Issue by zanona** [reworkcss/rework-vars#40]
Hey guys, congrats for the initiative! Amazing work.

I was trying this on Chrome and it seems to work fine, but not sure if it follows the spec.
Although, I believe it would be a great addition if there could be a way to implement this perhaps?
#### input.css

``` css
  :root {
    --theme-color: blue;
  }
  :root.alt {
    --theme-color: green;
  }
  p {
    margin: 1em;
    color: var(--theme-color, red);
}
```
#### output.css

``` css
p  {
  margin: 1em;
  color: blue;
}
.alt p { color: green; }
```
