### ISSUE TITLE
Support overwriting/cascading variable values

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-vars#9]
At the moment, a complete map is produced before any substitutions. It would be more CSS-y (and match common expectations) to do the mapping and substitutions at the same time. Example of difference in output:

Original:

``` css
:root {
  var-color: green;
}

.test {
  color: var(color);
  var-color: red;
}
```

Yields:

``` css
:root {
  var-color: green;
}

.test {
  color: red;
  var-color: red;
}
```

Desired:

``` css
:root {
  var-color: green;
}

.test {
  color: green;
  var-color: red;
}
```

**Comment by tj** [comment]
hmm yeah either is fine with me, what's the spec say? I know they have some weird var resolution stuff that we can't really pull off without implementing specificity blah blah

**Comment by necolas** [comment]
Yeah, let's keep the simple global vars but just slightly rework the map-and-substitution so that it all takes place in one pass so you can use order-dependent overrides (like prefix-free allows).

**Comment by tj** [comment]
sounds good to me

**Comment by conradz** [comment]
If I understand this correctly, this removes the possibility of using `rework-vars` to provide customizability for a library. Previously I was using this so that I could for example make a library that defines `var-button-color: red;`, and then the user could import it using [rework-npm](https://github.com/conradz/rework-npm) and override the default variables from the library (e.g. provide `var-button-color: blue;`).

With these changes, this is currently impossible. The library defines the default variables, and then uses them. Any overriding done after the library is imported is not applied.

IMO it is more "css-y" to allow overridden global variables, since you can override CSS definitions (e.g. have `.test { color: red; } .test { color: blue; }`). Also, if I understand it correctly, the CSS vars spec would allow for having vars overridden.

**Comment by conradz** [comment]
Just to clarify, by "having vars overridden" I mean that the following would work:

``` css
:root {
  var-color: red;
}

.test {
  color: var(color);
}

:root {
  var-color: blue;
}

/* Expected output: */
.test {
  color: blue;
}
```

**Comment by necolas** [comment]
With the support for fallbacks, libraries shouldn't define customisable variables themselves. This plugin now works much more like CSS variables will.

``` css
.test {
  color: var(color, red);
}
```

outputs the following unless you define `var-color`

``` css
.test {
  color: red;
}
```
